FROM almalinux:9
LABEL author="amarnath" \
      company="devops" \
      topic="dockerfiles" \
      duration="2hrs"

# LABEL instruction adds metadata to the image. Metadata means description,owner,project name etc.
# LABEL instruction is mainly used to filter the images, it doesn't add any functionality